# Основные настройки
title: Название вашего сайта
description: Описание вашего сайта
url: "https://ваш-username.github.io" # URL вашего сайта
baseurl: "" # Оставьте пустым, если ваш сайт находится в корневой директории репозитория

# Ссылки на социальные сети
social:
  twitter: ваш_твиттер
  github: ваш_github
  # Добавьте другие социальные сети при необходимости

# Настройки сборки и отображения постов
theme: jekyll-theme-minimal # Выберите тему из предустановленных или установленных вами
markdown: kramdown # Используйте kramdown для обработки markdown

# Конфигурация Jekyll
plugins:
  - jekyll-feed # Плагин для генерации RSS-ленты
  - jekyll-seo-tag # Плагин для SEO мета-тегов
  # Другие плагины, если необходимо

# Настройки для разработки
# Установите значение в true, если хотите видеть дополнительную информацию о сборке
verbose: false 
# Установите значение в true, чтобы автоматически перегенерировать сайт при изменении файлов
watch: true

# Настройки для GitHub Pages
# Отключите использование страницы 404, если у вас есть своя страница ошибки 404
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title.html # Формат ссылок на посты
